captainVersion: 4
services:
  $$cap_appname-db:
    image: supabase/postgres:14.1.0.89
    environment:
      POSTGRES_PASSWORD: $$cap_postgres_password
      POSTGRES_DB: $$cap_postgres_db
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data
    caproverExtra:
      containerHttpPort: '5432'
    ports:
      - "5432:5432"
  $$cap_appname-studio:
    image: supabase/studio:latest
    environment:
      STUDIO_PG_META_URL: http://$$cap_appname-meta:8080
      SUPABASE_URL: http://$$cap_appname-kong:8000
      SUPABASE_PUBLIC_URL: $$cap_public_url
      SUPABASE_ANON_KEY: $$cap_anon_key
      SUPABASE_SERVICE_KEY: $$cap_service_key
    ports:
      - "3000:3000"
  $$cap_appname-kong:
    image: kong:2.1
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
    volumes:
      - $$cap_appname-kong-config:/var/lib/kong
    ports:
      - "8000:8000"
  $$cap_appname-auth:
    image: supabase/gotrue:v2.5.21
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:$$cap_postgres_password@$$cap_appname-db:5432/$$cap_postgres_db
      JWT_SECRET: $$cap_jwt_secret
      API_EXTERNAL_URL: $$cap_public_url
    ports:
      - "9999:9999"
  $$cap_appname-rest:
    image: postgrest/postgrest:v9.0.0
    environment:
      PGRST_DB_URI: postgres://postgres:$$cap_postgres_password@$$cap_appname-db:5432/$$cap_postgres_db
      PGRST_JWT_SECRET: $$cap_jwt_secret
    ports:
      - "3000:3000"
  $$cap_appname-realtime:
    image: supabase/realtime:v0.22.4
    environment:
      DB_HOST: $$cap_appname-db
      DB_NAME: $$cap_postgres_db
      DB_USER: postgres
      DB_PASSWORD: $$cap_postgres_password
      PORT: 4000
      JWT_SECRET: $$cap_jwt_secret
    ports:
      - "4000:4000"
  $$cap_appname-storage:
    image: supabase/storage-api:v0.43.11
    environment:
      ANON_KEY: $$cap_anon_key
      SERVICE_KEY: $$cap_service_key
      POSTGREST_URL: http://$$cap_appname-rest:3000
      PGRST_JWT_SECRET: $$cap_jwt_secret
      DATABASE_URL: postgres://postgres:$$cap_postgres_password@$$cap_appname-db:5432/$$cap_postgres_db
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: s3
      GLOBAL_S3_BUCKET: $$cap_s3_bucket
      GLOBAL_S3_ENDPOINT: $$cap_s3_endpoint
      GLOBAL_S3_PROTOCOL: $$cap_s3_protocol
      GLOBAL_S3_FORCE_PATH_STYLE: $$cap_s3_force_path_style
      AWS_ACCESS_KEY_ID: $$cap_s3_access_key_id
      AWS_SECRET_ACCESS_KEY: $$cap_s3_secret_access_key
      AWS_DEFAULT_REGION: $$cap_s3_region
      TENANT_ID: stub
      REGION: $$cap_s3_region
      ENABLE_IMAGE_TRANSFORMATION: "true"
      IMGPROXY_URL: http://$$cap_appname-imgproxy:5001
    ports:
      - "5000:5000"
  $$cap_appname-meta:
    image: supabase/postgres-meta:v0.28.0
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: $$cap_appname-db
      PG_META_DB_PASSWORD: $$cap_postgres_password
    ports:
      - "8080:8080"
  $$cap_appname-imgproxy:
    image: darthsim/imgproxy:v3.8.0
    environment:
      IMGPROXY_BIND: ":5001"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /
      IMGPROXY_USE_ETAG: "true"
    ports:
      - "5001:5001"
caproverOneClickApp:
  variables:
    - id: $$cap_postgres_password
      label: PostgreSQL Password
      description: Password for the PostgreSQL database
      validRegex: /.{8,}/
    - id: $$cap_postgres_db
      label: PostgreSQL Database Name
      description: Name of the PostgreSQL database
      defaultValue: postgres
    - id: $$cap_public_url
      label: Public URL
      description: Public URL for your Supabase instance
    - id: $$cap_anon_key
      label: Anon Key
      description: Anon key for Supabase authentication
    - id: $$cap_service_key
      label: Service Key
      description: Service key for Supabase authentication
    - id: $$cap_jwt_secret
      label: JWT Secret
      description: Secret key for JWT authentication
      validRegex: /.{32,}/
    - id: $$cap_s3_bucket
      label: S3 Bucket Name
      description: Name of your S3 bucket
    - id: $$cap_s3_endpoint
      label: S3 Endpoint
      description: Endpoint URL for your S3 service
    - id: $$cap_s3_protocol
      label: S3 Protocol
      description: Protocol for S3 (http or https)
      defaultValue: https
    - id: $$cap_s3_force_path_style
      label: S3 Force Path Style
      description: Use path-style addressing for S3 (true or false)
      defaultValue: "false"
    - id: $$cap_s3_access_key_id
      label: S3 Access Key ID
      description: Access Key ID for your S3 service
    - id: $$cap_s3_secret_access_key
      label: S3 Secret Access Key
      description: Secret Access Key for your S3 service
    - id: $$cap_s3_region
      label: S3 Region
      description: Region for your S3 service
  instructions:
    start: This one-click app will deploy the Supabase stack with S3 storage on your CapRover instance.
    end: Supabase has been successfully deployed! Access the Studio at $$cap_appname-studio:3000
  displayName: Supabase Stack with S3 Storage
  description: Deploy Supabase, an open source Firebase alternative, with S3 storage
